// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationTestMVC.LeaderboardAPI.Models;

#nullable disable

namespace WebApplicationTestMVC.LeaderboardAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231206235533_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("WebApplicationTestMVC.LeaderboardAPI.Models.Attempt", b =>
                {
                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("INTEGER");

                    b.ToTable("Attempt");
                });
#pragma warning restore 612, 618
        }
    }
}
